const fs = require('fs');
if (fs.existsSync('bot.env')) require('dotenv').config({ path: './bot.env' });

module.exports = {
  BOT_URL: process.env.BOT_URL || "https://raw.githubusercontent.com/ArslanMDofficial/ARSLAN-MD-DATA/refs/heads/main/datafile.json",
  AUTO_SITE: process.env.AUTO_SITE || "https://arslan-apis.vercel.app",
  BAND_URL: process.env.BAND_URL || "https://raw.githubusercontent.com/ArslanMDofficial/ARSLAN-MD-DATA/refs/heads/main/bandusers.json",
  REPO_LINK: process.env.REPO_LINK || "https://github.com/Arslan-MD/KIRA-MD",
  REPO_NAME: process.env.REPO_NAME || "SHITSU-MD",
  BOT_NAME: process.env.BOT_NAME || "SHITSU-MD",
  DESCRIPTION: process.env.DESCRIPTION || "SHITSU MD POWERFULL WHATSAPP BOT",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "",
  OWNER_NAME: process.env.OWNER_NAME || "SHITSU-MD Official",
  ST_SAVE: process.env.ST_SAVE || "SHITSU-MD-STATUS-SERVER",
  BIO_TEXT: process.env.BIO_TEXT || "SHITSU-MD-OFFICIAL",
  AUTO_STATUS_MSG: process.env.AUTO_STATUS_MSG || "*`STATUS SEEN BY SHITSU-MD`* _*POWERD BY*_ *SHITSU-MD Official Whtsapp Bot*",
  STATUS_MSG: process.env.STATUS_MSG || "Thanks for status! ❤️",
  STATUS_EMOJI: process.env.STATUS_EMOJI || "💚",
  FOOTER: process.env.FOOTER || "SHITSU-MD",
  COPYRIGHT: process.env.COPYRIGHT || "*㋛ SHITSU-MD OFFICIAL*",
  VERSION: process.env.VERSION || "9.0.0",
  NEWSLETTER: process.env.NEWSLETTER || "120363348739987203@newsletter",
  WA_CHANNEL: process.env.WA_CHANNEL || "https://whatsapp.com/channel",
  INSTA: process.env.INSTA || "https://Instagram.com/Lovely_boy_dil",
  PREFIX: process.env.PREFIX || ".",
  API_BASE: process.env.API_BASE || "https://arslan-apis.vercel.app/",
  API_KEY: process.env.API_KEY || "arslanmdofficialadmin",
  ALIVE_IMG: process.env.ALIVE_IMG || "https://shyra.edgeone.app/alive.jpg",
  OWNER_IMG: process.env.OWNER_IMG || "https://files.catbox.moe/n2c0lu.png",
  CONVERT_IMG: process.env.CONVERT_IMG || "https://shyra.edgeone.app/convert.jpg",
  AI_IMG: process.env.AI_IMG || "https://shyra.edgeone.app/Ai.jpg",
  SEARCH_IMG: process.env.SEARCH_IMG || "https://shyra.edgeone.app/search.jpg",
  DOWNLOAD_IMG: process.env.DOWNLOAD_IMG || "https://shyra.edgeone.app/download.jpg",
  MAIN_IMG: process.env.MAIN_IMG || "https://shyra.edgeone.app/bot-img.jpg",
  GROUP_IMG: process.env.GROUP_IMG || "https://shyra.edgeone.app/Group.jpg",
  FUN_IMG: process.env.FUN_IMG || "https://shyra.edgeone.app/fun.jpg",
  TOOLS_IMG: process.env.TOOLS_IMG || "https://shyra.edgeone.app/Tools.jpg",
  OTHER_IMG: process.env.OTHER_IMG || "https://shyra.edgeone.app/other.jpg",
  MOVIE_IMG: process.env.MOVIE_IMG || "https://shyra.edgeone.app/movie.jpg",
  NEWS_IMG: process.env.NEWS_IMG || "https://shyra.edgeone.app/News.jpg",
  PP_IMG: process.env.PP_IMG || "https://shyra.edgeone.app/Education.jpg",
  INFO_IMG: process.env.INFO_IMG || "https://shyra.edgeone.app/info.jpg",
  SYS_IMG: process.env.SYS_IMG || "https://shyra.edgeone.app/system.jpg",
  SET_IMG: process.env.SET_IMG || "https://shyra.edgeone.app/settings.jpg"
};
